apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test2
    run.tanzu.vmware.com/tkr: v1.33.6---vmware.1-fips-vkr.2
  name: test2
  namespace: tmc-sm
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.67.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.97.0.0/16
  topology:
    class: builtin-generic-v3.4.0
    classNamespace: vmware-system-vks-public
    controlPlane:
      metadata: {}
      replicas: 1
      variables:
        overrides:
        - name: vmClass
          value: best-effort-small
    variables:
      - name: volumes
        value: []
      - name: storageClass
        value: nfs-pool-1-policy
      - name: vmClass
        value: ""
      - name: vsphereOptions
        value:
          persistentVolumes:
            defaultStorageClass: nfs-pool-1-policy
      - name: kubernetes
        value:
          certificateRotation:
            enabled: true
            renewalDaysBeforeExpiry: 90
      - name: osConfiguration
        value:
          trust:
            additionalTrustedCAs:
              - caCert:
                  secretRef:
                    key: ca.crt
                    name: harbor-ca
    version: v1.33.6+vmware.1-fips
    workers:
      machineDeployments:
      - class: node-pool
        metadata: {}
        name: md-0
        replicas: 1
        variables:
          overrides:
          - name: vmClass
            value: best-effort-small
          - name: storageClass
            value: nfs-pool-1-policy